### ISSUE TITLE
Possible to port FSR 2.0 / 2.1 / 2.2?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [JakobPCoder/ReshadeTFAA#8]
I see ReShade community comments about you can't have TAA because no motion vector  
but TFAA did emulate motion vector behavior (far better than other ReShade TAA port without motion vector)

Could this be possible to use with FSR 2?  
Lossless Scaling / magpie community also mentioned there are no motion vector, so you can't have FSR 2 series  
I know ReShade have no API for upscale,  
but just 1920x1080 to 1920x1080, use it as antialiasing method?

**Comment by Spacellary** [comment]
👀
That'd be amazing but I think we'll need proper motion vectors for that, maybe they add them in the upcoming graphics update.

**Comment by mhtvsSFrpHdE** [comment]
> 👀
> That'd be amazing but I think we'll need proper motion vectors for that, maybe they add them in the upcoming graphics update.

@Spacellary So qUINT / DRME is still not real motion vector that can compatible with FSR 2 requirement?

**Comment by Spacellary** [comment]
I asked Alex if DRME or his FFXIV_MOTIONVECTORS could be used to implement FSR2, and he replied:

> no

But hey, maybe there's a way we haven't found out yet.

**Comment by mhtvsSFrpHdE** [comment]
> I asked Alex if DRME or his FFXIV_MOTIONVECTORS could be used to implement FSR2, and he replied:
> 
> > no
> 
> > also ffxiv is mainly cpu constrained in most scenarios. if you're struggling in e.g. limsa, it's not because of your gpu most likely
> 
> > also do note that the REST addon with all bells and whistles does add an additional cpu overhead (the UIONLY version very much less so)
> 
> I think most people should stick to the UIONLY version of REST.
> 
> But hey, maybe there's a way we haven't found out yet.

Thank you for the information!  
This issue shall closed then.

**Comment by JakobPCoder** [comment]
No, you cannot use motion vectors alone to achieve DLSS or FSR with motion data. The issue is that all samples are taken at the same rasterized positions, and ReShade currently cannot force the game to output with a resolution scaling step.

There are tools like Magpie and Lossless Scaling that handle this by capturing the game and projecting the upscaled output to a new window. However, this process introduces latency and falls outside the scope of ReShade.

If someone were to develop a ReShade addon that replicates what Magpie does, then implementing versions of FSR and DLSS within ReShade would become possible.

**Comment by Spacellary** [comment]
@JakobPCoder As of right now the best option seems to be using [OptiScaler](https://github.com/cdozdil/OptiScaler) since the game now has native DLSS implementation, you can benefit from FSR3.1.2 instead from it, which should work on all GPUs. Honestly it's **very** good and clean (NativeAA supported) and works well with ReShade for me.

Just sharing for others that might still be looking for something like that.

Cheers!
